CREATE TABLE IF NOT EXISTS "CM_MENU" (
	"MENU_ID"	TEXT NOT NULL,
	"MENU_NM"	TEXT NOT NULL,
	"PARENT_MENU_ID"	TEXT,
	"MENU_LEVEL"	INTEGER,
	"MENU_URL"	TEXT,
	"MENU_ICON" TEXT,
	"SEQ"	INTEGER,
	"USE_YN"	TEXT DEFAULT 'Y',
	"DESCRIPTION"	TEXT,
	"CREATE_USER_ID"	TEXT,
	"CREATE_DT"	TEXT,
	"UPDATE_USER_ID"	TEXT,
	"UPDATE_DT"	TEXT
);
CREATE TABLE IF NOT EXISTS "CM_ITEM" (
	"ITEM_ID"	TEXT NOT NULL,
	"MENU_ID"	TEXT,
	"X"	INTEGER,
	"Y"	INTEGER,
	"W"	INTEGER,
	"H"	INTEGER,
	"I"	INTEGER,
	"MIN_W"	INTEGER,
	"MAX_W"	INTEGER,
	"MIN_H"	INTEGER,
	"MAX_H"	INTEGER,
	"SEQ"	INTEGER,
	"USE_YN"	INTEGER,
	"DESCRIPTION"	INTEGER,
	"CREATE_ID"	TEXT,
	"CREATE_DT"	TEXT,
	"UPDATE_ID"	TEXT,
	"UPDATE_DT"	TEXT
);
CREATE TABLE IF NOT EXISTS "CM_INTERFACE" (
	"IF_ID"	TEXT NOT NULL,
	"IF_TYPE"	TEXT NOT NULL,
	"IF_VALUE"	TEXT NOT NULL,
	"IF_PARSING"	TEXT,
	"SEQ"	INTEGER,
	"USE_YN"	TEXT,
	"DESCRIPTION"	TEXT,
	"CREATE_ID"	TEXT,
	"CREATE_DT"	TEXT,
	"UPDATE_ID"	TEXT,
	"UPDATE_DT"	TEXT
);
CREATE TABLE IF NOT EXISTS "CM_ITEM_INTERFACE_R" (
	"ITEM_ID"	TEXT NOT NULL,
	"IF_ID"	TEXT NOT NULL,
	"SEQ"	INTEGER,
	"USE_YN"	TEXT,
	"DESCRIPTION"	TEXT,
	"CREATE_ID"	TEXT,
	"CREATE_DT"	TEXT,
	"UPDATE_ID"	TEXT,
	"UPDATE_DT"	TEXT
)
